messaging:
  tweets:                             # nazwa kolejki
    TweetProcessor:                   # nazwa klasy
      filter: "language = 'java'"     # JMS message selector

jobs:
  tweet_remover:
    job:  TweetRemover
    cron: '*/30 * * * * ?'

